# Generated by Django 4.1.7 on 2023-05-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_product_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
